### ISSUE TITLE
VM settings crash (MacOS)

### ISSUE THREAD

**Issue by MichalTuleja** [insanemal/86box_manager_py#12]
The program crashes when trying to edit the machine settings and the 86box binary is not available.

OS: MacOS 12.5
Python 3.8.5

```
python3 src/86BoxManager.py                                        134 ↵ main
Traceback (most recent call last):
  File "/Users/michal/work/86box_manager_py/src/mainw.py", line 175, in configButtonClicked
    p = subprocess.Popen(ops)
  File "/Users/michal/opt/anaconda3/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/michal/opt/anaconda3/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/Users/michal/temp/winnt4/86Box.app'
[1]    71613 abort      python3 src/86BoxManager.py
```

**Comment by gtorresini** [comment]
MacOS apps are bundle/folders. You need to add the remaining path of the bundle.

Solution is here:
[](https://github.com/insanemal/86box_manager_py/issues/6)
